apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: skaffold
build:
  artifacts:
    - image: aitakynsultan/k8s
      context: kubtest
deploy:
  kubectl:
    manifests:
      - manifests/deployment.yaml
      - manifests/service.yaml
      - manifests/ingress.yaml
